export const EXCEPTION = "EXCEPTION";


export const SIGN_UP = "SIGN_UP_NORMAL"; 
export const SIGN_UP_ERRORS = "SIGN_UP_ERRORS";
export const SIGN_IN = "SIGN_IN_NORMAL";
export const SIGN_IN_ERRORS = "SIGN_IN_NORMAL_ERRORS";
export const SIGN_IN_GOOGLE = "SIGN_IN_GOOGLE";
export const SIGN_IN_GOOGLE_ERRORS = "SIGN_IN_GOOGLE_ERRORS";
export const SIGN_IN_FACEBOOK = "SIGN_IN_FACEBOOK";
export const SIGN_IN_FACEBOOK_ERRORS = "SIGN_IN_FACEBOOK_ERRORS";